name: soil-calc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi=0.104.1
  - uvicorn=0.24.0
  - python-jose=3.3.0
  - python-multipart=0.0.6
  - pydantic=2.4.2
  - python-dotenv=1.0.0
  - sqlalchemy=2.0.23
  - pytest=7.4.3
  - streamlit
  - pip
  - pip:
    - "python-jose[cryptography]==3.3.0"